config/routes.rb
Rails.application.routes.draw do

root to: 'articles#index'

resources :articles 
resources :authors
resources :author_sessions, only: [ :new, :create, :destroy ]

get 'login'  => 'author_sessions#new'
get 'logout' => 'author_sessions#destroy'

get 'tagged' => 'articles#tagged', :as => 'tagged'  
get 'featured' => 'articles#featured', :as => 'featured'   

end

app/models/article.rb
class Article < ActiveRecord::Base

default_scope {order(created_at: :desc)}  
 
	 
	has_many :attachments 
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	acts_as_taggable_on :countries, :genres, :types, :tags


	def tag_list
 	 self.tags.map(&:name).join(', ')
	end

	 

	def preview
		body[0..300]  +  "  "
	end 
  
 	 def self.featured_article
    	where :featured => true 
  	end
  	 def self.unfeatured_article
    	where :featured => false 
  	end

   
end 

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper

	http_basic_authenticate_with :name => "bucks", :password => "testing"

	before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@articles = Article.featured_article + Article.unfeatured_article 

  		 
	end
	def show
		@article = Article.find(params[:id])
	end
	def new
		@article = Article.new

	end
	def create
    	@article = Article.new(article_params)
   		@article.save

   		flash.notice = "Article '#{@article.title}' has been created!"

   		redirect_to article_path(@article)
  	end
  	def edit
 		@article = Article.find(params[:id])
	end
	def destroy
 		@article = Article.find(params[:id])
 		@article.destroy

 		flash.notice = "Article '#{@article.title}' has been deleted!"

 		redirect_to articles_path

	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' Updated!"

		redirect_to article_path(@article)
	end
	def tagged
 		 if params[:tag].present? 
   		 @articles = Article.tagged_with(params[:tag])
 		 else 
   		 @articles = Article.all
  		end  
	end

	 
  
 
	  




	 
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, message: 'Logged In successfully')
		else
			flash.now.alert = "Login Failed"
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:authors, message: 'Logged Out')
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  before_filter :zero_authors_or_authenticated, only: [:new, :create]

  before_filter :require_login, except: [:new, :create]

def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/countrytags_controller.rb
class CountrytagsController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_filter :require_login, only: [:destroy]

	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "Tag '#{@tag.title}' has been deleted!"

		redirect_to tags_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
include ActsAsTaggableOn::TagsHelper

	def article_params
		params.require(:article).permit(:title, :body, :biog, :dead_line, :label, :website, :facebook, :twitter, :tag_list,   :featured, :image)
	end
	
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/countrytags_helper.rb
module CountrytagsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/articles/_form.html.erb
<div class="contentshow"><%= form_for(@article, html: {multipart: true}) do |f| %>

	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.label :biog %><br />
		<%= f.text_area :biog %>
	</p>
	<p>
		<%= f.label :dead_line %><br />
		<%= f.text_field :dead_line %>
	</p>
	<p>
		<%= f.label :label %><br />
		<%= f.text_field :label %>
	</p>
	<p>
		<%= f.label :website %><br />
		<%= f.text_field :website %>
	</p>
	<p>
		<%= f.label :facebook %><br />
		<%= f.text_field :facebook %>
	</p>
	<p>
		<%= f.label :twitter %><br />
		<%= f.text_field :twitter %>
	</p>
	
	<p> <%= f.label :tags %>
<%= f.text_field :tag_list %>
	 </p> 
	 
 
	 <p><%= f.label :featured? %>
	 <%= f.check_box :featured  %>

</p>
	 
	 
	<p>
		<% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
  		<% end %>
  		<%= f.label :image, "Attach a New Image" %><br />
 		 <%= f.file_field :image %>
	</p>
	<p>
		<%= f.submit  class: 'myButton'%>

	</p>

<% end %>

 </div>

app/views/articles/edit.html.erb
<h1> Edit an Article </h1>

<%= render partial: 'form' %>

&nbsp;<%= link_to "Delete Article", article_path(@article), class: 'myButton', method: :delete, data: {confirm:"Are You Sure You Want To Delete This?"} %><br /><br />

 &nbsp;<a href="../" class="myButton"><span>&nbsp;&lt; </span>Back To List</a>

app/views/articles/index.html.erb
<h1 class="main_art_tit2"> Who's Looking List</h1>

 <br /> <br /> 
 <table width="100%">
 <tr>
 <td valign="top">
 <form id="countrysearch">
<label> Countries: </label>
<div class="select-style">
<select>
    <option value="country1">United Kingdom</option>
    <option value="country2">United States</option>
    <option value="country3">Worldwide</option>
    <option value="country4">Europe</option>
  </select>
  </div>
  </form>
  </td> 
  <td valign="top">
   <form id="genresearch">
<label> Genre: </label>
<div class="select-style">
 <select>
    <option value="genre1">Pop</option>
    <option value="genre2">Rock</option>
    <option value="genre3">House</option>
    <option value="genre4">Dance</option>
  </select>
  </div> 
   </form>
   </td>
    <td valign="top">
   <form id="typesearch">
<label> Type: </label>
<div class="select-style">
 <select>
    <option value="type1">Top Line</option>
    <option value="type2">Producer</option>
    <option value="type3">Songwriter</option> 
  </select>
  </div>
</form>
</td>
<td>
<input type="submit" value="Filter">
</td>
 </tr>
 </table>
 <br /> <br /> <br /> <br />
<ul id="articles">
  <% @articles.each do |article| %>
 


	
<% if article.featured == true %>

       <li class="featured">  
  <%= link_to article.title, article_path(article) %>
   
    <span class="date">
  <% if false %><%= article.created_at.strftime('%A, %-d %B %Y ') %><% end %> <%= article.dead_line %></span>   <div id="clear"></div><div class="moveup"><hr><br />
     <p class="article_main"><%= article.preview %>...  <%= link_to "Read More", article_path(article) %></p>  

     </div>
     <br /> 

  </li>
  <% else %>
   <li class="notfeatured">  
  <%= link_to article.title, article_path(article) %>
   
    <span class="date">
  <% if false %><%= article.created_at.strftime('%A, %-d %B %Y ') %><% end %> <%= article.dead_line %></span>   <div id="clear"></div><div class="moveup"><hr><br />
     <p class="article_main"><%= article.preview %>...  <%= link_to "Read More", article_path(article) %></p>  

     </div>
     <br /> 

  </li>
      <% end %>

  <% end %>
</ul><% if false %>
<%= will_paginate @articles, :page_links => false %><% end %><br /><br />
<% if logged_in? %>
<%= link_to "Create a New Brief", new_article_path, class: 'myButton' %>
<% end %>

 <br />


 

app/views/articles/index.js.haml
$('.articles').append('#{escape_javascript(render partial: "shared/articles", :locals => { :articles => @articles })}');
$('a.load-more-briefs').attr('href', '#{articles_path page: @articles.next_page}');
 
- unless @articles.next_page
  $('a.load-more-briefs').remove();

app/views/articles/new.html.erb
<h1> Create a New Article </h1>

<%= render partial: 'form' %>


<br />&nbsp;&nbsp;<a href="../" class="myButton"><span>&nbsp;&lt; </span>Back To List</a>

app/views/articles/priority.html.erb
<ul id="articles">
  <% @articles.each do |article| %>
	<li> 
	<%= link_to article.title, article_path(article) %>
	</li>
  <% end %>
</ul>
<% if logged_in? %>
<%= link_to "Create a New Article", new_article_path, class: 'new_article' %>
<% end %>
<br><br>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/articles/show.html.erb
<div class="contentshow"><h1 class="main_art_tit"> <%= @article.title %> </h1>
 <br />

<p>
		<% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
  		<% end %>
  		
	</p><hr>
 <h3 class="brief"><span class="labeldesc">Brief </span></h3><hr><p class="main_article_body"><br /><%= @article.body %><br /><br /><%= @article.biog %> </p><br /><hr> 



<table width="93%">
<tr>
<td width="15%" valign="top"><h3><span class="labeldesc">Deadline </span></h3></td>
<td width="85%" valign="top"><h3><span class="deet"><%= @article.dead_line %></span> </h3></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="100%"><hr></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="15%" valign="top"><h3><span class="labeldesc">Label </span></h3></td>
<td width="85%" valign="top"><h3><span class="deet"><%= @article.label %></span> </h3></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="100%"><hr></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="15%" valign="top"><h3><span class="labeldesc">Links </span></h3></td>
<td width="85%" valign="top"><h3><span class="deet"><a href="http://<%= @article.website %>">Website</a>  
 <a href="http://<%= @article.facebook %>">Facebook</a>  <a href="http://<%= @article.twitter %>">Twitter</a></span> </h3></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="100%"><hr></td>
</tr>
</table>
<table width="93%">
<tr>
<td width="15%" valign="top"><h3><span class="labeldesc">Tags </span></h3></td>
<td width="85%" valign="top"><h3><span class="deet"><% @article.tags.any? %>
  <% @article.tags.each do |tag| %>
  <%= link_to tag.name, tagged_url(:tag => tag.name) %>

<% end %>
  
 
</span></h3></td>
</tr>


</table>

 
	 




 <br />

<br /><a href="../" class="myButton"><span>&nbsp;&lt; </span>Back To List</a>
 
<% if logged_in? %>
&nbsp;<a href="<%= edit_article_path(@article) %>" class="myButton">Edit</a><br />

 <% end %>
 </div>

app/views/articles/tagged.html.erb
 
<ul id="articles">
  <% @articles.each do |article| %>
	<li> 
	<%= link_to article.title, article_path(article) %>
	</li><br><br>
  <% end %>
</ul>
<% if logged_in? %><br><br>
<%= link_to "Create a New Article", new_article_path, class: 'myButton' %>
<% end %>
<br><br>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email  %>
    <%= text_field_tag :email  %> 
    <br/> <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div> <br/>
  <div class="actions">
    <%= submit_tag "Login"  %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= author.password %></td>
        <td><%= author.password_confirmation %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Who's Looking List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
</head>
<body>
<p class="flash"><%= flash.notice %></p>
<div id="container">
<div class="bannerimg">
<a href="http://www.bucksmusicgroup.co.uk" target="_blank"><img src="../../newbanner.png"></a>
</div>
<div id="content">
<%= yield %>
<br />

</div>
</div>
</body>
</html>

app/views/tagged/index.html.erb
 <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %><br>

app/views/tagged/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
<% @tag.articles.each do |article| %>
		<li><%= link_to article.title, article_path(article) %></li>
<% end %>
</ul><br>
<%= link_to "<< Back To All Tags", tags_path(@tag) %>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/tags/index.html.erb
<h1><%= link_to "All Tags", tags_path(@tag) %></h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
    <%= link_to tag.name, tag_path(tag) %>

    </li>
  <% end %>
</ul> 
<% if logged_in? %>
<%= link_to "Delete Tag", tags_path(@tag), method: :delete, data: {confirm:"Are You Sure You Want To Delete This?"} %>
<% end %>
<%= link_to "<< Back to Articles List", articles_path %>